apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: pod1
    image: nginx
    ports:
        - containerPort: 80
    livenessProbe:
      tcpSocket:
        port: 801
      initialDelaySeconds: 2
      periodSeconds: 2
      successThreshold: 1
      failureThreshold: 1
~                                  
