apiVersion: v1
kind: Service
metadata:
  name: app-nginx
  namespace: nginx
  labels:
    run: app-nginx
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    run: app-nginx
